site_name: Magnus
site_description: "Pipelines made easy"
strict: true
repo_url: https://github.com/AstraZeneca/magnus-core

docs_dir: "docs"
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  font:
    code: Roboto Mono
    text: Roboto
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky

# Extensions
markdown_extensions:
  - pymdownx.snippets:
      base_path: "docs"
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 2
  - attr_list
  - md_in_html

plugins:
  - search

nav:
  - "Home": "index.md"
  - "Getting started":
      - "Installation": "getting_started/installation.md"
      - "Example Run": "getting_started/example.md"
      - "Explanation - input": "getting_started/brief-concepts-input.md"
      - "Explanation - output": "getting_started/brief-concepts-output.md"
      - "Example Deployment": "getting_started/example-deployment.md"
      - "Wrap up": "getting_started/wrap-up.md"
      - "Why magnus": "getting_started/why-magnus.md"
  # - "Tutorial":
  #     - "Overview": "tutorial/overview.md"
  #     - "Single notebook": "tutorial/single-notebook.md"
  #     - "Modular notebooks": "tutorial/modular-notebooks.md"
  #     - "Switching configs": "tutorial/switching-configs.md"
  #     - "Using parallels": "tutorial/using-parallel.md"
  #     - "Dynamic looping": "tutorial/dynamic-looping.md"
  #     - "Modular pipelines": "tutorial/modular-dags.md"
  #     - "Script based": "tutorial/script-based.md"
  #     - "What next?": "tutorial/wrap-up.md"
  - "Concepts":
      - "Node": "concepts/nodes.md"
      - "Command types": "concepts/command-types.md"
      - "Dag": "concepts/dag.md"
      - "Catalog":
          - "Overview": "concepts/catalog.md"
          - "Do Nothing Catalog": "concepts/catalog-implementations/do-nothing.md"
          - "File System": "concepts/catalog-implementations/file-system.md"
      - "Secrets":
          - "Overview": "concepts/secrets.md"
          - "Dot Env": "concepts/secrets-implementations/dot-env.md"
          - "Do Nothing": "concepts/secrets-implementations/do-nothing.md"
          - "Env Secrets Manager": "concepts/secrets-implementations/env-secrets-manager.md"
      - "Run Log":
          - "Overview": "concepts/run-log.md"
          - "Buffered": "concepts/run-log-implementations/bufferred.md"
          - "File System": "concepts/run-log-implementations/file-system.md"
          - "Chunked File System": "concepts/run-log-implementations/chunked-fs.md"
      - "Experiment Tracking":
          - "Overview": "concepts/experiment-tracking.md"
      - "Integration":
          - "Overview": "concepts/integration.md"
      - "Compute Mode":
          - "Overview": "concepts/modes.md"
          - "Local": "concepts/modes-implementations/local.md"
          - "Local Container": "concepts/modes-implementations/local-container.md"
          - "Demo Renderer": "concepts/modes-implementations/demo-renderer.md"
  - "Command Line":
      - "Options": "command-line.md"
  - "How do I?":
      - "How Do I": "how-do-i.md"
  - "Examples":
      - "Overview": "examples.md"
  - "Extensions":
      - "Guide to Extensions": "extensions/extensions.md"
  - "Releases": "RELEASES.md"
