site_name: Magnus
site_description: "Pipelines made easy"
strict: true
repo_url: https://github.com/AstraZeneca/magnus-core

docs_dir: "docs"
theme:
  logo: assets/logo.png
  favicon: assets/favicon.png
  name: material
  font:
    code: Roboto Mono
    text: Roboto
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    - scheme: default
      primary: amber
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: amber
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky

# Extensions
markdown_extensions:
  - pymdownx.snippets:
      base_path: "."
  - admonition
  - codehilite
  - footnotes
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      separator: "_"
      toc_depth: 2
  - attr_list
  - md_in_html

plugins:
  - search
  - section-index

nav:
  - "Home": "index.md"
  - "Getting started":
      - "getting_started/installation.md"
      - "Example Run": "getting_started/example.md"
      - "Explanation - input": "getting_started/brief-concepts-input.md"
      - "Explanation - output": "getting_started/brief-concepts-output.md"
      - "Example Deployment": "getting_started/example-deployment.md"
      - "Wrap up": "getting_started/wrap-up.md"
      - "Why magnus": "getting_started/why-magnus.md"
  # - "Tutorial":
  #     - "Overview": "tutorial/overview.md"
  #     - "Single notebook": "tutorial/single-notebook.md"
  #     - "Modular notebooks": "tutorial/modular-notebooks.md"
  #     - "Switching configs": "tutorial/switching-configs.md"
  #     - "Using parallels": "tutorial/using-parallel.md"
  #     - "Dynamic looping": "tutorial/dynamic-looping.md"
  #     - "Modular pipelines": "tutorial/modular-dags.md"
  #     - "Script based": "tutorial/script-based.md"
  #     - "What next?": "tutorial/wrap-up.md"
  - "Concepts":
      - "Node": "concepts/nodes.md"
      - "Command types": "concepts/command-types.md"
      - "Dag": "concepts/dag.md"
      - "Catalog": "concepts/catalog.md"
      - "Secrets": "concepts/secrets.md"
      - "Run Log": "concepts/run-log.md"
      - "Experiment Tracking": "concepts/experiment-tracking.md"
      #- "Integration": "concepts/integration.md"
      - "Executors": "concepts/executor.md"

  - "Command Line":
      - "command-line.md"
  - "Executors":
      - "Local": "concepts/executor-implementations/local.md"
      - "Local Container": "concepts/executor-implementations/local-container.md"
      - "Kubeflow": "concepts/executor-implementations/kfp.md"
      - "Argo": "concepts/executor-implementations/argo.md"
      - "K8s-job": "concepts/executor-implementations/k8s-job.md"
      - "Demo Renderer": "concepts/executor-implementations/demo-renderer.md"
  - "Run Logs":
      - "Buffered": "concepts/run-log-implementations/bufferred.md"
      - "File System": "concepts/run-log-implementations/file-system.md"
      - "Chunked File System": "concepts/run-log-implementations/chunked-fs.md"
      - "S3": "concepts/run-log-implementations/s3.md"
      - "Chunked S3": "concepts/run-log-implementations/chunked-s3.md"
  - "Catalog":
      - "Do Nothing Catalog": "concepts/catalog-implementations/do-nothing.md"
      - "File System": "concepts/catalog-implementations/file-system.md"
      - "S3": "concepts/catalog-implementations/s3.md"
  - "Secrets":
      - "Dot Env": "concepts/secrets-implementations/dot-env.md"
      - "Do Nothing": "concepts/secrets-implementations/do-nothing.md"
      - "Env Secrets Manager": "concepts/secrets-implementations/env-secrets-manager.md"
      #- "AWS Secrets Manager": "concepts/secrets-implementations/aws_secrets_manager.md"
  - "Experiment Tracking":
      - "MLFlow": "concepts/experiment-implementations/mlflow.md"
  - "How do I?":
      - "how-do-i.md"
  - "Examples":
      - "examples.md"
  - "Extensions":
      - "extensions/extensions.md"
