[tool.poetry]
name = "magnus"
version = "0.1.0"
description = "A Compute agnostic pipelining software"
authors = ["Vijay Vammi <vijay.vammi@astrazeneca.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
"ruamel.yaml" = "*"
"ruamel.yaml.clib" = "*"
yachalk = "*"
dataclasses-json = "*"
docker ={ version = "*", optional = true } 

[tool.poetry.extras]
docker = ['docker']
 
[tool.poetry.dev-dependencies]
astroid = "*"
attrs = "*"
autopep8 = "*"
coverage = "*"
iniconfig = "*"
isort = "*"
lazy-object-proxy = "*"
mccabe = "*"
pluggy = "*"
py = "*"
pycodestyle = "*"
pylint = "*"
pyparsing = "*"
pytest = "*"
pytest-cov = "*"
pytest-mock = "*"
toml = "*"
wrapt = "*"
mkdocs = "*"
mkdocs-material = "*"

[tool.poetry.scripts]
magnus= 'magnus.cli:main'


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
