executor:
  type: "argo" # (1)
  config:
    image: magnus-example:latest # (2)
    persistent_volumes: # (3)
      - name: magnus-volume
        mount_path: /mnt
    resources:
      limits: # (4)
        cpu: "500m"
        memory: "512Mi"
        gpu: 0

run_log_store: # (5)
  type: file-system
  config:
    log_folder: /mnt/run_log_store # (6)

catalog:
  type: do-nothing

secrets:
  type: do-nothing

experiment_tracker:
  type: do-nothing
