executor:
  type: local # (1)

run_log_store:
  type: buffered # (2)

catalog:
  type: do-nothing # (3)

secrets:
  type: do-nothing # (4)

experiment_tracker: # (5)
  type: mlflow
  config:
    server_url: http://127.0.0.1:8080
