name: docs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install poetry
      - run: |
          python -m poetry install --only docs
          poetry run mkdocs gh-deploy --force
