on:
  pull_request:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: python -m pip install poetry
      - run: |
          python -m poetry install

          `python -m poetry env info -p`/bin/activate
          poetry run tox
