on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - "bug_mlflow"

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: python -m pip install python-semantic-release
      - name: Figure version
        id: last_tag
        run: |
          VERSION=$(semantic-release print-version --verbosity=DEBUG)
          echo $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
      - name: Tag git
        env:
          LAST_TAG: ${{ steps.last_tag.outputs.result }}
        run: |
          git tag -a $LAST_TAG -m "Release from GH action"
          git push origin $LAST_TAG
      # - name: Publish to PyPI
      #   env:
      #     PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      #   run: |
      #     poetry config pypi-token.pypi $PYPI_TOKEN
      #     poetry publish --build
